/*
 * This file is generated by jOOQ.
 */
package com.arjvik.arjmart.orderqueueconsumer.schema.tables.records;


import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Inventory;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class InventoryRecord extends UpdatableRecordImpl<InventoryRecord> implements Record4<Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = -779734674;

    /**
     * Setter for <code>arjmart.Inventory.SKU</code>.
     */
    public void setSku(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>arjmart.Inventory.SKU</code>.
     */
    public Integer getSku() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>arjmart.Inventory.ItemAttributeID</code>.
     */
    public void setItemattributeid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>arjmart.Inventory.ItemAttributeID</code>.
     */
    public Integer getItemattributeid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>arjmart.Inventory.LocationID</code>.
     */
    public void setLocationid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>arjmart.Inventory.LocationID</code>.
     */
    public Integer getLocationid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>arjmart.Inventory.InventoryAmount</code>.
     */
    public void setInventoryamount(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>arjmart.Inventory.InventoryAmount</code>.
     */
    public Integer getInventoryamount() {
        return (Integer) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Integer, Integer, Integer> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Integer, Integer> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Inventory.INVENTORY.SKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Inventory.INVENTORY.ITEMATTRIBUTEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Inventory.INVENTORY.LOCATIONID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Inventory.INVENTORY.INVENTORYAMOUNT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getItemattributeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getLocationid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getInventoryamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getItemattributeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getLocationid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getInventoryamount();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value1(Integer value) {
        setSku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value2(Integer value) {
        setItemattributeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value3(Integer value) {
        setLocationid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord value4(Integer value) {
        setInventoryamount(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public InventoryRecord values(Integer value1, Integer value2, Integer value3, Integer value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached InventoryRecord
     */
    public InventoryRecord() {
        super(Inventory.INVENTORY);
    }

    /**
     * Create a detached, initialised InventoryRecord
     */
    public InventoryRecord(Integer sku, Integer itemattributeid, Integer locationid, Integer inventoryamount) {
        super(Inventory.INVENTORY);

        set(0, sku);
        set(1, itemattributeid);
        set(2, locationid);
        set(3, inventoryamount);
    }
}
