/*
 * This file is generated by jOOQ.
 */
package com.arjvik.arjmart.orderqueueconsumer.schema.tables.records;


import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemattributemaster;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemattributemasterRecord extends UpdatableRecordImpl<ItemattributemasterRecord> implements Record4<Integer, Integer, String, String> {

    private static final long serialVersionUID = -387836097;

    /**
     * Setter for <code>arjmart.ItemAttributeMaster.SKU</code>.
     */
    public void setSku(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>arjmart.ItemAttributeMaster.SKU</code>.
     */
    public Integer getSku() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>arjmart.ItemAttributeMaster.ItemAttributeID</code>.
     */
    public void setItemattributeid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>arjmart.ItemAttributeMaster.ItemAttributeID</code>.
     */
    public Integer getItemattributeid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>arjmart.ItemAttributeMaster.Color</code>.
     */
    public void setColor(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>arjmart.ItemAttributeMaster.Color</code>.
     */
    public String getColor() {
        return (String) get(2);
    }

    /**
     * Setter for <code>arjmart.ItemAttributeMaster.Size</code>.
     */
    public void setSize(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>arjmart.ItemAttributeMaster.Size</code>.
     */
    public String getSize() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Itemattributemaster.ITEMATTRIBUTEMASTER.SKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Itemattributemaster.ITEMATTRIBUTEMASTER.ITEMATTRIBUTEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Itemattributemaster.ITEMATTRIBUTEMASTER.COLOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Itemattributemaster.ITEMATTRIBUTEMASTER.SIZE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getItemattributeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getItemattributeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getColor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getSize();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemattributemasterRecord value1(Integer value) {
        setSku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemattributemasterRecord value2(Integer value) {
        setItemattributeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemattributemasterRecord value3(String value) {
        setColor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemattributemasterRecord value4(String value) {
        setSize(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ItemattributemasterRecord values(Integer value1, Integer value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ItemattributemasterRecord
     */
    public ItemattributemasterRecord() {
        super(Itemattributemaster.ITEMATTRIBUTEMASTER);
    }

    /**
     * Create a detached, initialised ItemattributemasterRecord
     */
    public ItemattributemasterRecord(Integer sku, Integer itemattributeid, String color, String size) {
        super(Itemattributemaster.ITEMATTRIBUTEMASTER);

        set(0, sku);
        set(1, itemattributeid);
        set(2, color);
        set(3, size);
    }
}
