/*
 * This file is generated by jOOQ.
 */
package com.arjvik.arjmart.orderqueueconsumer.schema.tables.records;


import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Orderline;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderlineRecord extends UpdatableRecordImpl<OrderlineRecord> implements Record6<Integer, Integer, Integer, Integer, Integer, String> {

    private static final long serialVersionUID = -240473011;

    /**
     * Setter for <code>arjmart.OrderLine.OrderID</code>.
     */
    public void setOrderid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>arjmart.OrderLine.OrderID</code>.
     */
    public Integer getOrderid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>arjmart.OrderLine.OrderLineID</code>.
     */
    public void setOrderlineid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>arjmart.OrderLine.OrderLineID</code>.
     */
    public Integer getOrderlineid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>arjmart.OrderLine.SKU</code>.
     */
    public void setSku(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>arjmart.OrderLine.SKU</code>.
     */
    public Integer getSku() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>arjmart.OrderLine.ItemAttributeID</code>.
     */
    public void setItemattributeid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>arjmart.OrderLine.ItemAttributeID</code>.
     */
    public Integer getItemattributeid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>arjmart.OrderLine.Quantity</code>.
     */
    public void setQuantity(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>arjmart.OrderLine.Quantity</code>.
     */
    public Integer getQuantity() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>arjmart.OrderLine.Status</code>.
     */
    public void setStatus(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>arjmart.OrderLine.Status</code>.
     */
    public String getStatus() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<Integer, Integer> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Integer, Integer, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Orderline.ORDERLINE.ORDERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Orderline.ORDERLINE.ORDERLINEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Orderline.ORDERLINE.SKU;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Orderline.ORDERLINE.ITEMATTRIBUTEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return Orderline.ORDERLINE.QUANTITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Orderline.ORDERLINE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOrderlineid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getItemattributeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOrderid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOrderlineid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getSku();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getItemattributeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getQuantity();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value1(Integer value) {
        setOrderid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value2(Integer value) {
        setOrderlineid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value3(Integer value) {
        setSku(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value4(Integer value) {
        setItemattributeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value5(Integer value) {
        setQuantity(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord value6(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OrderlineRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrderlineRecord
     */
    public OrderlineRecord() {
        super(Orderline.ORDERLINE);
    }

    /**
     * Create a detached, initialised OrderlineRecord
     */
    public OrderlineRecord(Integer orderid, Integer orderlineid, Integer sku, Integer itemattributeid, Integer quantity, String status) {
        super(Orderline.ORDERLINE);

        set(0, orderid);
        set(1, orderlineid);
        set(2, sku);
        set(3, itemattributeid);
        set(4, quantity);
        set(5, status);
    }
}
