/*
 * This file is generated by jOOQ.
 */
package com.arjvik.arjmart.orderqueueconsumer.schema;


import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Inventory;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemattributemaster;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemmaster;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemprice;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Locationmaster;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Order;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Orderline;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.User;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Userroles;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Arjmart extends SchemaImpl {

    private static final long serialVersionUID = 1061153412;

    /**
     * The reference instance of <code>arjmart</code>
     */
    public static final Arjmart ARJMART = new Arjmart();

    /**
     * The table <code>arjmart.Inventory</code>.
     */
    public final Inventory INVENTORY = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Inventory.INVENTORY;

    /**
     * The table <code>arjmart.ItemAttributeMaster</code>.
     */
    public final Itemattributemaster ITEMATTRIBUTEMASTER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemattributemaster.ITEMATTRIBUTEMASTER;

    /**
     * The table <code>arjmart.ItemMaster</code>.
     */
    public final Itemmaster ITEMMASTER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemmaster.ITEMMASTER;

    /**
     * The table <code>arjmart.ItemPrice</code>.
     */
    public final Itemprice ITEMPRICE = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemprice.ITEMPRICE;

    /**
     * The table <code>arjmart.LocationMaster</code>.
     */
    public final Locationmaster LOCATIONMASTER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Locationmaster.LOCATIONMASTER;

    /**
     * The table <code>arjmart.Order</code>.
     */
    public final Order ORDER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Order.ORDER;

    /**
     * The table <code>arjmart.OrderLine</code>.
     */
    public final Orderline ORDERLINE = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Orderline.ORDERLINE;

    /**
     * The table <code>arjmart.User</code>.
     */
    public final User USER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.User.USER;

    /**
     * The table <code>arjmart.UserRoles</code>.
     */
    public final Userroles USERROLES = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Userroles.USERROLES;

    /**
     * No further instances allowed
     */
    private Arjmart() {
        super("arjmart", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Inventory.INVENTORY,
            Itemattributemaster.ITEMATTRIBUTEMASTER,
            Itemmaster.ITEMMASTER,
            Itemprice.ITEMPRICE,
            Locationmaster.LOCATIONMASTER,
            Order.ORDER,
            Orderline.ORDERLINE,
            User.USER,
            Userroles.USERROLES);
    }
}
