/*
 * This file is generated by jOOQ.
 */
package com.arjvik.arjmart.orderqueueconsumer.schema;


import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Inventory;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemattributemaster;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemmaster;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemprice;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Locationmaster;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Order;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Orderline;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.User;
import com.arjvik.arjmart.orderqueueconsumer.schema.tables.Userroles;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in arjmart
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.2"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>arjmart.Inventory</code>.
     */
    public static final Inventory INVENTORY = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Inventory.INVENTORY;

    /**
     * The table <code>arjmart.ItemAttributeMaster</code>.
     */
    public static final Itemattributemaster ITEMATTRIBUTEMASTER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemattributemaster.ITEMATTRIBUTEMASTER;

    /**
     * The table <code>arjmart.ItemMaster</code>.
     */
    public static final Itemmaster ITEMMASTER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemmaster.ITEMMASTER;

    /**
     * The table <code>arjmart.ItemPrice</code>.
     */
    public static final Itemprice ITEMPRICE = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Itemprice.ITEMPRICE;

    /**
     * The table <code>arjmart.LocationMaster</code>.
     */
    public static final Locationmaster LOCATIONMASTER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Locationmaster.LOCATIONMASTER;

    /**
     * The table <code>arjmart.Order</code>.
     */
    public static final Order ORDER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Order.ORDER;

    /**
     * The table <code>arjmart.OrderLine</code>.
     */
    public static final Orderline ORDERLINE = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Orderline.ORDERLINE;

    /**
     * The table <code>arjmart.User</code>.
     */
    public static final User USER = com.arjvik.arjmart.orderqueueconsumer.schema.tables.User.USER;

    /**
     * The table <code>arjmart.UserRoles</code>.
     */
    public static final Userroles USERROLES = com.arjvik.arjmart.orderqueueconsumer.schema.tables.Userroles.USERROLES;
}
